name: 'github-actions-details-action'
description: 'Collect and comment with details about GitHub Actions on PRs'

inputs:
  search_token:
    description: 'GitHub Personal Access Token (PAT)'
    required: true
  token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  report_type:
    description: 'comment, output, both'
    required: true
    default: 'comment'
  allow_list_path:
    description: 'Path to the GitHub Actions allow list YML within the repository'
    default: 'github-actions-allow-list.yml'
outputs:
  actionName:
    description: 'Action name/path'
  isGitHubVerified:
    description: 'Is the GitHub Actions organization verified'
  isSecurityPolicyEnabled:
    description: 'Is the GitHub Actions organization security policy enabled'
  stars:
    description: 'Number of stars for the GitHub Actions'
  knownVulnerabilities:
    description: 'Number of known vulnerabilities for the GitHub Actions'
  license:
    description: 'License for the GitHub Actions'
  latestRelease:
    description: 'Latest release for the GitHub Actions'
  topics:
    description: 'Topics for the GitHub Actions'
  languages:
    description: 'Languages for the GitHub Actions'
  homepage:
    description: 'Homepage for the GitHub Actions'
  description:
    description: 'Description for the GitHub Actions'
  url:
    description: 'URL for the GitHub Actions'
  actionRequestedVersion:
    description: 'Requested version for the GitHub Actions'
  contributors:
    description: 'Contributors for the GitHub Actions'
  watchers:
    description: 'Watchers for the GitHub Actions'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'zoom-in'
  color: 'green'
