name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CI: true

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 20
        experimental: [false]
        # include:
        #   - node-version: lts/*
        #     experimental: true

    continue-on-error: ${{ matrix.experimental }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}-${{ matrix.experimental }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Check repository dependency graph
        uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM install
        run: npm install --ignore-scripts --pure-lockfile

      - name: NPM build
        run: npm run build --if-present

      - name: NPM test
        run: npm run test --if-present

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - name: Success
        run: echo "success"
