name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CI: true

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 20
        experimental: [false]
        # include:
        #   - node-version: lts/*
        #     experimental: true

    continue-on-error: ${{ matrix.experimental }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}-${{ matrix.experimental }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check repository dependency graph
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM install
        run: npm install --ignore-scripts --pure-lockfile

      - name: NPM build
        run: npm run build --if-present

      - name: NPM test
        run: npm run test --if-present

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - name: Success
        run: echo "success"
